version: '3.8'  # Versi docker-compose yang digunakan

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"  # Sesuaikan memori sesuai kebutuhan
      - "xpack.security.enabled=false"  # Menonaktifkan keamanan
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  mysql-development:
    container_name: mysql-development
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'development'
      MYSQL_USER: 'korie'
      MYSQL_PASSWORD: 'korie123'
      MYSQL_ROOT_PASSWORD: 'korie123'
    volumes:
      - mysql-development:/var/lib/mysql

volumes:
  esdata:
    driver: local
  mysql-development: